### ISSUE TITLE
Integrate commands for making outputs

### ISSUE THREAD

**Issue by sj-aws** [awslabs/damo#105]
There are multiple commands for making some outputs: `show`, `status`, `record`, and `fmt_json`.  Let's integrate those into one command (probably `show`) for simplicity.

**Comment by sj-aws** [comment]
This will also helps supporting yaml-format DAMON parameters formatting[1].  For example,

```
# damo show damon_params --format json
# damo show damon_params --format yaml
```

[1] https://github.com/awslabs/damo/pull/97#issuecomment-2150451395

**Comment by sjp38** [comment]
Actually, nearly every damo commands except DAMON controlling (start/stop/tune) are somewhat for making some output.  Maybe further categorizing is better...

**Comment by sjp38** [comment]
The plan is to replace old workflow for collecting data and visualizing.  For this, we will introduce three new commands.

- `collect`: Collect DAMON outputs and system status
- `read`: Visualize the collected data
  - Can do the collecting of the data itself, for convenient usage.
  - Aims to replace `show`, `status`, and `report`.
  - The name may better to be changed.
- `args`: Generate complex arguments for other commands
  - Such as DAMON parameters and snapshot formatting parameters (`--format_region` of `damo show`)
  - Aims to replace `fmt_json` and support `yaml` format DAMON parameters

**Comment by sjp38** [comment]
`args` command is added with support of `json` and `yaml` format DAMON parameters generation.

**Comment by sj-aws** [comment]
After 2024-09-05, we will[1] use damonitor repo[2] as the only main repo for GitHub.  To continue discussion of this issue on the repo, I just created a new issue[3] there.  Please use the new issue for followup discussions.

Closing this issue in favor of the new one on the damonitor repo. Please ask me to open this again if you cannot continue the discussion from the new issue.

[1] https://lore.kernel.org/20240813232158.83903-1-sj@kernel.org
[2] https://github.com/damonitor/damo
[3] https://github.com/damonitor/damo/issues/11
