### ISSUE TITLE
something wrong when run "./damo report heats --heatmap stdout --stdout_heatmap_color emotion"?

### ISSUE THREAD

**Issue by wangrongwei** [awslabs/damo#27]
Hi
Thanks for your great tools! I am studying and testing how to use this tools. But I have a trouble in usage.
I can not get the output style like "https://github.com/awslabs/damo/blob/next/images/masim_zigzag_heatmap_ascii.png" shown when I test in my system. But "./damo/damo report raw" works, it print following log:

400036705000-400036718000(  76.000 KiB):        0
400036718000-400036719000(   4.000 KiB):        15
400036719000-40003671d000(  16.000 KiB):        0
40003671d000-40003671f000(   8.000 KiB):        12
40003671f000-400036722000(  12.000 KiB):        0
400036722000-400036723000(   4.000 KiB):        12
400036723000-400036739000(  88.000 KiB):        0
400036739000-40003673a000(   4.000 KiB):        14
40003673a000-40003673e000(  16.000 KiB):        0
40003673e000-400036745000(  28.000 KiB):        0
400036745000-400036746000(   4.000 KiB):        20
400036746000-400036756000(  64.000 KiB):        0
ffffe1a18000-ffffe1a39000( 132.000 KiB):        0

I am not sure whether I miss something. 

Thanks!

**Comment by sjp38** [comment]
I unsure why you closed this issue though the fix was not made.  I made a fix for this: https://github.com/awslabs/damo/commit/a6bf6ade74b7ccdadd8461f5893118136a99033f

If that doesn't work for you, please open this issue again.

**Comment by wangrongwei** [comment]
> I am unsure why you closed this issue while the fix was not made. I made a fix for this: [a6bf6ad](https://github.com/awslabs/damo/commit/a6bf6ade74b7ccdadd8461f5893118136a99033f)
> 
> If that doesn't work for you, please open this issue again.

Hi
I found it works well using latest version in weeks ago.  And thought you had fixed it, so, closed this issue.

Anyway, it wroks for me. Thanks very much!
