### ISSUE TITLE
Record rbuf size has no effect on damon built with kernel 5.15.0-rc3

### ISSUE THREAD

**Issue by lrrountr** [awslabs/damo#28]
While trying to use the -l (--rbuf) length of record result buffer argument, I see no effect on it.

Usage example:
`./damo record -l 4096 $(pidof masim)`

The debugfs does not has the record fie which was previously used when running an rc for 5.14 version prior to mainline integration

```
ls -la /sys/kernel/debug/damon/
total 0
drwxr-xr-x. 2 root root 0 Oct 13 14:09 .
drwx------. 39 root root 0 Oct 13 14:09 ..
-rw-------. 1 root root 0 Oct 14 12:42 attrs
-rw-------. 1 root root 0 Oct 13 14:09 kdamond_pid
-rw-------. 1 root root 0 Oct 13 14:09 mk_contexts
-rw-------. 1 root root 0 Oct 14 12:41 monitor_on
-rw-------. 1 root root 0 Oct 13 14:09 rm_contexts
-rw-------. 1 root root 0 Oct 14 12:41 target_ids
```

Has this feature stopped being supported? Or is it a missing configuration in kernel flags?

**Comment by sj-aws** [comment]
The patches for `record` file is not merged in the mainline yet.  The patches will be posted soon.  Actually, the patches were [posted](https://lore.kernel.org/linux-mm/20211008094509.16179-1-sj@kernel.org/), but there was a question on quatized benefit of this, and a request on better formatting.  So I am working for those now.

If you need the feature, you could apply the patches from `damon/next` [tree](https://git.kernel.org/sj/h/damon/next).  If you think the feature is really beneficial for you and therefore you want it to be escalated, you could make some voice on the [thread](https://lore.kernel.org/linux-mm/20211008094509.16179-1-sj@kernel.org/).

Anyway, the UX from `damo` makes no sense in this case.  It would be better to check the case and warn the user.
