### ISSUE TITLE
option --numa_node 0 fails and default to the largest region

### ISSUE THREAD

**Issue by simini** [awslabs/damo#33]
When trying to run with paddr targetting the NUMA node with ID=0, the code is treating numa_node=0 as numa_node=false here:
https://github.com/awslabs/damo/blob/next/record.py#L164 
Hence tracing this area is not possible (unless you are lucky and it matches the default region).

**Comment by sj-aws** [comment]
Thank you so much for this report!  I fixed this with https://github.com/damonitor/damo/commit/56aa308c2847dcb0e905c1a0127b77c18b6e2194
