### ISSUE TITLE
Damo fails to start

### ISSUE THREAD

**Issue by jjang3** [awslabs/damo#34]
Hello!

I attempted to use the `sudo damo start` option, but it seems to raise an error, as shown below:
![image](https://user-images.githubusercontent.com/42549923/180662182-0d0733f1-a889-4226-9b73-aa18690b4e30.png)

Upon searching through the source code, I found that this function is indeed defined in `_damon.py`, so I found this error quite weird!
![image](https://user-images.githubusercontent.com/42549923/180662209-9e57309e-dfe1-4a9b-86ac-d87e687c4f38.png)

Thank you very much.
Kind regards.

**Comment by sj-aws** [comment]
Thank you very much for this report!

**Comment by sj-aws** [comment]
This was due to mistakes from recent huge code refactoring.  Just fixed the messes and pushed the fixes to the next and master branch.  I further released v1.4.0 with the fixes.  Please open this again if it doesn't works for you.
