### ISSUE TITLE
damo recording for multi process/thread program

### ISSUE THREAD

**Issue by honggyukim** [awslabs/damo#44]
Hi @sjp38,

It's been a while but I would like to ask you a question regarding damo recording for multi process/thread programs.

I would like to record the memory access pattern of a target program, but it's written in a shell script and it invokes a python script that creates multiple threads internally.

In this case, which `pid` should I put as a target of `damo`?

I have tried to put the pid of the python script insdie the shell script, but it shows nothing in the output of the following command.
```
$ ./damo report heats --heatmap stdout --stdout_heatmap_color emotion
(... prints multiple empty lines ...)
# access_frequency:  0  1  2  3  4  5  6  7  8  9
# x-axis: space (94647110262784-94738634076144: 85.238 GiB)
# y-axis: time (24214084546000-25696152599000: 24 m 42.068 s)
# resolution: 80x40 (1.065 GiB and 37.052 s for each character)
```
I have tested the heatmap output of `masim` with `zigzag.cfg` and `stairs.cfg` and they showed the expected output.

Could you please help? Thanks!

**Comment by honggyukim** [comment]
The target program was executed for about 25 minutes.

**Comment by honggyukim** [comment]
If possible, it'd be really nice if there is a way to record the target program and its children processes or threads together.

**Comment by sj-aws** [comment]
Hi Honggyu,

> which pid should I put as a target of damo?

It should be the process that doing the memory access that you want to monitor.  So the pid of the python script, which you tried, should be the right one.  I think the monitoring and recording was properly done, but the reporting has some problem.  Because virtual address space usually contains huge holes between mapped regions, heatmap visualization usually result in only black screen, because its overwhelmed by the huge holes.  The command tries to find virtual address ranges that having meaningful accesses, but it could fail sometimes.  You can specify the ranges using `--address_range` option.  You can also use `--guide` option to get some suggestions for `--address_range`.  I think you could also further check if the monitoring was done correctly by using `damo report raw` or `damo report wss`.  If it is `--address_range` problem, `damo report wss` should show some meaningful numbers.  Please try those and let me know the results.

> it'd be really nice if there is a way to record the target program and its children processes or threads together.

Thank you for suggesting this great idea.  It would be really helpful.  I will add it to `TODO`.

**Comment by sj-aws** [comment]
> I found that there was another request about cgroup based monitoring

You're correct.  The status is same to the reply (https://lore.kernel.org/lkml/20230508214019.80558-1-sj@kernel.org/T/#m19de002473a6fc74a61f36482d27d61ec2ed98bd) at the moment.

**Comment by honggyukim** [comment]
Thanks. I hope this feature can be implemented in the near future :)

**Comment by honggyukim** [comment]
Thanks a lot. I will keep an eye on this ticket :)

**Comment by honggyukim** [comment]
I have one more question. I have recorded another workload called from https://github.com/facebook/CacheLib.

In this example, it creates multiple threads in the workload and the [config](https://github.com/facebook/CacheLib/blob/main/cachelib/cachebench/test_configs/hit_ratio/cdn/config.json) shows "numThreads" is 48.

The heatmap result of this recording shows as follows.
![image](https://github.com/awslabs/damo/assets/19642328/f836bbd1-1693-477a-905a-76b521d20298)

I thought that `damo` cannot record multiple threads so I changed "numThreads" to 1 to record all the memory accesses, but the heatmap result shows much less memory accesses as follows.
![image](https://github.com/awslabs/damo/assets/19642328/e0012ae5-5d8e-4f65-9779-af4eebe7433b)

I have some doubts about whether the `damo` is able to record multiple threads that have the same address space, but not possible for multiple processes. Could you please clarify this? Thanks!

**Comment by sj-aws** [comment]
Thank you for sharing the nice plot!

> whether the damo is able to record multiple threads that have the same address space, but not possible for multiple processes

Your guess is correct.  DAMON can monitor multiple threads in single process.  It can also record multiple processes.  And `damo` supports the features, so it can record all.  You wouldn't need to reduce the number of threads in above example.

Please note that you should explicitly specify each pid of process you want to monitor/record.  Hence accesses of child processes are not automatically monitored and recorded.  But for multiple threads sharing same pid, damo monitors/records all threads' accesses.

**Comment by sj-aws** [comment]
Hi Honggyu,

I just implemented the feature and pushed to the `next` branch.  You can now automatically add childs as targets for `damo record` by adding `--include_childs` option, like below.

```
$ cat test.sh
#!/bin/bash

echo "test.sh pid: $BASHPID"
sleep 2
../masim/masim ../masim/configs/stairs.cfg
$ sudo ./damo record --include_childs "./test.sh"
test.sh pid: 1855
Press Ctrl+C to stop
initial phase:                38,160 accesses/msec, 10002 msecs run
phase 0:                      40,013 accesses/msec, 5002 msecs run
phase 1:                      39,950 accesses/msec, 5000 msecs run
phase 2:                      40,055 accesses/msec, 5000 msecs run
phase 3:                      40,055 accesses/msec, 5000 msecs run
phase 4:                      40,081 accesses/msec, 5000 msecs run
phase 5:                      40,178 accesses/msec, 5001 msecs run
phase 6:                      40,057 accesses/msec, 5003 msecs run
phase 7:                      40,152 accesses/msec, 5001 msecs run
phase 8:                      40,134 accesses/msec, 5000 msecs run
phase 9:                      40,231 accesses/msec, 5001 msecs run
[ perf record: Woken up 7 times to write data ]
[ perf record: Captured and wrote 2.059 MB damon.data (14074 samples) ]
$ sudo ./damo report heats --heatmap stdout
11112211111111211112221111111122222221111111111222212111111112221112222222210000
22222222111111111222211111111111111111111111111111111111111112222221111111100000
11111111111111111111111111111111111111111111112211112212222222222222222222210000
11111111111111111111111111111112221111111112222221111111111111111111111111110000
11111111111111121111111111111111111111111111111111122222222222111111111111100000
11111111111111111111111111111111111111111111111111111100000111111111333333210000
00000000000000000000000000000000000000000000000000000000000000000000788888850000
00000000000000000000000000000000000000000000000000000000000000000000788888850000
00000000000000000000000000000000000000000000000000000000000000000000788888850000
00000000000000000000000000000000000000000000000000000000000037777777111111100000
00000000000000000000000000000000000000000000000000000000000048888888000000000000
00000000000000000000000000000000000000000000000000000000000048888888000000000000
00000000000000000000000000000000000000000000000000000344443335444444000000000000
00000000000000000000000000000000000000000000000000000888888840000000000000000000
00000000000000000000000000000000000000000000000000000888888840000000000000000000
00000000000000000000000000000000000000000000011111111777777740000000000000000000
00000000000000000000000000000000000000000000058888887000000000000000000000000000
00000000000000000000000000000000000000000000058888887000000000000000000000000000
00000000000000000000000000000000000000000000058888887000000000000000000000000000
00000000000000000000000000000000000001666666631111111000000000000000000000000000
00000000000000000000000000000000000001888888830000000000000000000000000000000000
00000000000000000000000000000000000001888888830000000000000000000000000000000000
00000000000000000000000000000023333333444444410000000000000000000000000000000000
00000000000000000000000000000068888886000000000000000000000000000000000000000000
00000000000000000000000000000068888886000000000000000000000000000000000000000000
00000000000000000000000000000067777776000000000000000000000000000000000000000000
00000000000000000000002788888820000000000000000000000000000000000000000000000000
00000000000000000000002888888820000000000000000000000000000000000000000000000000
00000000000000000000002888888820000000000000000000000000000000000000000000000000
00000000000000055555555422222200000000000000000000000000000000000000000000000000
00000000000000078888886000000000000000000000000000000000000000000000000000000000
00000000000000078888885000000000000000000000000000000000000000000000000000000000
00000001222222255555553000000000000000000000000000000000000000000000000000000000
00000003888888810000000000000000000000000000000000000000000000000000000000000000
00000003888888810000000000000000000000000000000000000000000000000000000000000000
00000003888888810000000000000000000000000000000000000000000000000000000000000000
88777775100000000000000000000000000000000000000000000000000000000000000000000000
88888884000000000000000000000000000000000000000000000000000000000000000000000000
88888884000000000000000000000000000000000000000000000000000000000000000000000000
33333331000000000000000000000000000000000000000000000000000000000000000000000000
# access_frequency:  0  1  2  3  4  5  6  7  8  9
# x-axis: space (140187374567424-140187480371184: 100.902 MiB)
# y-axis: time (1836617502000-1896215093000: 59.598 s)
# resolution: 80x40 (1.261 MiB and 1.490 s for each character)
$
```

Note that it works for only commands target arguments at the moment.

**Comment by sj-aws** [comment]
The feature will be included in the next release, which is aimed to be tomorrow.

**Comment by honggyukim** [comment]
Hi SeongJae,

> I just implemented the feature and pushed to the next branch.

Wow. Thank you very much for the support! I've just tested it and also see that it works fine with multiple processes.

> You can now automatically add childs as targets for damo record by adding --include_childs option

I have a few comments or requests as follows.
1. Can we rename `--include_childs` to `--follow_fork` or `--follow_fork_child`? I think `childs` looks incorrect English word or it should be `children`.
2. Can we enable this option by default and provide a way to exclude children processes with `--exclude_fork_child`?

Thanks again!

**Comment by honggyukim** [comment]
> fork sounds like a little bit too direct to the underlying mechanism. I also feel follow is not super-clear about what it will do. What do you think about --include_children or track_children?

I recommended to add `follow` in the option name just like `set follow-fork-mode mode` in gdb.
https://sourceware.org/gdb/onlinedocs/gdb/Forks.html

If you feel `follow` isn't clear than how about `--with_child_pids`? I feel that it's not clear what children means in `--include_chlidren`.

> I'm worrying if it could be a behavior change that could make some surprises to others who depend on current behavior.

OK. I'm fine with adding an option to follow children processes then. That's also the same way that gdb does.

**Comment by sj-aws** [comment]
> just like `set follow-fork-mode` mode in gdb.

I think `follow` might be not the best term here, mainly because `follow` could mean going to the destination leaving the current one behind.  In case of gdb, it is also used in the meaning (follow the execution flow, leaving the current one behind), to my understanding.

What the option does is, periodically checking the child processes and adding those to the monitoring targets list.  Hence, I think `follow` is not the best word here.  I'd prefer `include` or `add`, because we could read the command `damo record "workload.sh" --include_child` as "record the accesses from threads of workload.sh, including those of their child processes".

> how about `--with_child_pids`?

Sounds better, but `with` sounds a little bit implicit to me.  `pids`, too.  What about `--include_child_processes` or `--include_child_tasks`?

**Comment by honggyukim** [comment]
> What about --include_child_processes or --include_child_tasks?

`--include_child_tasks` sounds more clear to me. Could you please change the option name then? Thanks.

**Comment by sj-aws** [comment]
Sure, I will make the change soon :)

**Comment by honggyukim** [comment]
Thanks. I've found that it's changed by 429958e6382090962aca4a1eea6bb7e4510b8b1c. I will close this issue.
