### ISSUE TITLE
Inconsistent absolute time

### ISSUE THREAD

**Issue by DanielLee343** [awslabs/damo#49]
Hi,

I found this inconsistent absolute time generated by damo, with the time output from the program.
Specifically, I was playing with the masim and call this `GetTime()` first get into main and before main finishes.
```
void GetTime(char *identifier)
{
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    printf("%s at: %ld.%ld\n", identifier, ts.tv_sec, ts.tv_nsec);
}
```
The output shows 
```
in! at: 1016680.957450677
initial phase:	               22963 accesses/msec, 10000 msecs run
low phase 0:	               24710 accesses/msec, 5002 msecs run
high phase 0:	               24076 accesses/msec, 5003 msecs run
low phase 1:	               24500 accesses/msec, 5002 msecs run
high phase 1:	               23933 accesses/msec, 5000 msecs run
low phase 2:	               24348 accesses/msec, 5001 msecs run
high phase 2:	               23897 accesses/msec, 5002 msecs run
low phase 3:	               24417 accesses/msec, 5003 msecs run
high phase 3:	               23709 accesses/msec, 5003 msecs run
low phase 4:	               24469 accesses/msec, 5003 msecs run
high phase 4:	               23216 accesses/msec, 5002 msecs run
low phase 5:	               24526 accesses/msec, 5002 msecs run
high phase 5:	               23959 accesses/msec, 5000 msecs run
out! at: 1016751.151737409
```
As you see the time spans from `1016680` to `1016751`
However, when I use damo to get absolute time `sudo damo report heats --abs_time > abs_time.txt`, the first column, spans from `1016621500242000` to `1016686696412352`. As this is in nanosecond scale, so for second scale, it should be `1016621` to `1016686`, which is around ~60s ahead of what the program's output.

Is this a potential bug or is there something I missed? Thanks!

**Comment by sj-aws** [comment]
Hi @DanielLee343 , thank you for this question!


I tried to reproduce it as below, but was unable to.
```
$ git diff
diff --git a/masim.c b/masim.c
index 863a08fd2b03..989d9c58eaac 100644
--- a/masim.c
+++ b/masim.c
@@ -752,6 +752,10 @@ int main(int argc, char *argv[])
                        "  It defaults to \'configs/default\'",
        };
        int i;
+       struct timespec ts;
+
+       clock_gettime(CLOCK_MONOTONIC, &ts);
+       printf("start masim %ld.%ld\n", ts.tv_sec, ts.tv_nsec);

        argp_parse(&argp, argc, argv, ARGP_IN_ORDER, NULL, NULL);
        setlocale(LC_NUMERIC, "");
@@ -770,5 +774,8 @@ int main(int argc, char *argv[])
                exec_config(&config);
        }

+       clock_gettime(CLOCK_MONOTONIC, &ts);
+       printf("end masim %ld.%ld\n", ts.tv_sec, ts.tv_nsec);
+
        return 0;
 }
$ sudo ../damo/damo record "./masim ./configs/zigzag.cfg"
start masim 4871.815008703
Press Ctrl+C to stop
initial phase:                 8,580 accesses/msec, 10006 msecs run
low phase 0:                   8,978 accesses/msec, 5007 msecs run
[...]
end masim 4942.115499618
[ perf record: Woken up 5 times to write data ]
[ perf record: Captured and wrote 1.394 MB damon.data (9839 samples) ]
$ sudo ../damo/damo report heats --abs_time
4872594839000   0       14.236670261471852
[...]
4942639079780   205044090       0.0
```

The fact that the time difference in your case, about 60 seconds, is quite similar to that for the runtime of `masim`, makes me suspect `damo record` might indeed ran after the timestamp recording `masim` run is done.  Could you please double check it, or reproduce the issue again as I tried above and share the results?

**Comment by DanielLee343** [comment]
Thanks for responding! Unfortunately, I still have the issue even applied your diff patch.
```
cc@uc-lease-1:~/test_damo/masim$ sudo damo record "./masim ./configs/zigzag.cfg"
start masim 1061954.578585038
Press Ctrl+C to stop
[...]
end masim 1062024.769273875
[ perf record: Woken up 3 times to write data ]
[ perf record: Captured and wrote 2.353 MB damon.data (12465 samples) ]
cc@uc-lease-1:~/test_damo/masim$ sudo report heats --abs_time 
1061886942394000	0	0.0
[...]
1061956391638158	204966745	0.0
```
If you compare the result, actually `damo`'s abs_time is <strong>before</strong> program's timestamp, at around 68s. However, overall execution time produced by `damo` matches program's output (ie., 70s). 
Actually, I was using `damo` for other workloads in the first place and found this mismatch so I switched to test `masim` instead.
```
cc@uc-lease-1:~/test_damo/masim$ sudo damo version
1.8.1
cc@uc-lease-1:~/test_damo/masim$ gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by sj-aws** [comment]
Thank you for sharing the output!

As told before, `damo record` gets the time stamp from `perf script`.  The timestamp difference might already in `perf` output, or made in `damo` while processing it.

To show if the root cause is in `damo` or `perf`, could you please try saving the record as perf data, and reading the timestamp via `perf script`?  You could record it as perf data using `perf record -e damon:damon_aggregated`, or using `damo record` with `--output_type perf_data`.  For example,

```
$ sudo ./damo record "../masim/masim ../masim/configs/stairs.cfg" --output_type perf_data
start masim 59780.11057041
Press Ctrl+C to stop
[...]
end masim 59840.239729780
[ perf record: Woken up 5 times to write data ]
[ perf record: Captured and wrote 1.480 MB damon.data (10565 samples) ]
$ sudo perf script -i damon.data | head -n 1
       kdamond.0 20972 [031] 59783.282840: damon:damon_aggregated: target_id=0 nr_regions=20 94069127372800-94069138132992: 0 3
$ sudo perf script -i damon.data | tail -n 1
       kdamond.0 20972 [031] 59843.120635: damon:damon_aggregated: target_id=0 nr_regions=12 140733483024384-140733484412928: 0 569
```

The fourth column of the `perf script` output is the timestamp.  That is, `masim` ran during 59780-59840, while the recording has made during 59783-59843.  The difference of three seconds looks not a real problem but due to some internal delays between start of the masim and start of DAMON.

BTW, could you also share your use case that this is being problematic?

**Comment by DanielLee343** [comment]
After digging through, I suspect that my `damo` is using the default event in perf, rather than `damon:damon_aggregated` event. But I somehow cannot use the later event. Proof below:
```
cc@uc-lease-1:~/test_damo/masim$ sudo damo record "./masim ./configs/zigzag.cfg" --output_type perf_data
start masim 1128644.453954148
Press Ctrl+C to stop
[...]
end masim 1128714.665859665
[ perf record: Woken up 4 times to write data ]
[ perf record: Captured and wrote 2.260 MB damon.data (13592 samples) ]
cc@uc-lease-1:~/test_damo/masim$ sudo perf script -i damon.data | head -n 1
       kdamond.0 3130006 [019] 1128571.052272: damon:damon_aggregated: target_id=18446613511806845440 nr_regions=16 93824992231424-93824993132544: 0
cc@uc-lease-1:~/test_damo/masim$ sudo perf script -i damon.data | tail -n 1
       kdamond.0 3130006 [011] 1128640.657718: damon:damon_aggregated: target_id=18446613511806845440 nr_regions=20 140737488347136-140737488351232: 20
```
As you see `damo` (or `perf`) is 73s ahead of program's timestamp. 
Then I use `perf record` and run again:
```
cc@uc-lease-1:~/test_damo/masim$ ./masim ./configs/zigzag.cfg &
[1] 3132322
start masim 1129781.878791124
cc@uc-lease-1:~/test_damo/masim$ sudo perf record -e damon:damon_aggregated -p $(pidof masim)
[...]
end masim 1129852.69952909
[ perf record: Woken up 2 times to write data ]
[ perf record: Captured and wrote 0.017 MB perf.data ]
[1]+  Done                    ./masim ./configs/zigzag.cfg
cc@uc-lease-1:~/test_damo/masim$ sudo perf script -i perf.data | head -n 1
cc@uc-lease-1:~/test_damo/masim$ ls -lh perf.data
-rw------- 1 root root 50K Jun  3 17:43 perf.data
```
However, as you see `perf.data` is an empty file which means `perf` cannot use `damon:damon_aggregated` event.
Then I let `perf` use the default event by not specifying `-e` and it shows similar mismatch problem with `damo record`:
```
cc@uc-lease-1:~/test_damo/masim$ ./masim ./configs/zigzag.cfg &
[1] 3131283
start masim 1129177.94403679
cc@uc-lease-1:~/test_damo/masim$ sudo perf record -p $(pidof masim)
[...]
end masim 1129247.294772732
[ perf record: Woken up 42 times to write data ]
[ perf record: Captured and wrote 10.042 MB perf.data (262812 samples) ]
[1]+  Done                    ./masim ./configs/zigzag.cfg
cc@uc-lease-1:~/test_damo/masim$ sudo perf script -i perf.data | head -n 1
           masim 3131283 1129107.631340:          1 cycles:  ffffffffa9c7b8c4 native_write_msr+0x4 (/lib/modules/5.15.0/build/vmlinux)
cc@uc-lease-1:~/test_damo/masim$ sudo perf script -i perf.data | tail -n 1
           masim 3131283 1129173.335781:     644971 cycles:  ffffffffa9e62248 release_pages+0x438 (/lib/modules/5.15.0/build/vmlinux)
```
Something I tried here is to enable the `damon:damon_aggregated` in file system:
```
$ sudo cat /sys/kernel/tracing/events/damon/damon_aggregated/enable
0
$ echo 1 | sudo tee /sys/kernel/tracing/events/damon/damon_aggregated/enable
1
$ sudo cat /sys/kernel/tracing/events/damon/damon_aggregated/enable
1
```
And use `sudo perf record -e damon:damon_aggregated -p $(pidof masim)` to run again, but still cannot capture any result in `perf.data`. I use `ps aux | grep perf` and it shows `Sl+` state when running.
Some of my environment:
```
$ uname -r
5.15.0
$ perf version
perf version 5.15.0
$ if grep CONFIG_DAMON /boot/config-$(uname -r); then echo "installed"; fi
CONFIG_DAMON=y
CONFIG_DAMON_VADDR=y
CONFIG_DAMON_DBGFS=y
CONFIG_DAMON_KUNIT_TEST=y
CONFIG_DAMON_PADDR=y
CONFIG_DAMON_VADDR_KUNIT_TEST=y
CONFIG_DAMON_SYSFS=y
CONFIG_DAMON_DBGFS_KUNIT_TEST=y
CONFIG_DAMON_RECLAIM=y
CONFIG_DAMON_LRU_SORT=y
installed
```
The reason this mismatch is a problem to me is because I'm working on some HPC workload optimization and needs 1) memory access pattern from `damo` and 2) a shim layer (or code instrumentation) to capture the timestamp of some syscalls, eg., mmap(), brk(). Then I'll use the timestamp from 1) and 2) to cross-validate and get some insights about certain objects accesses of the workloads, thus the timestamp must be matched. An alternative is that I can manually add the timestamp difference to make them match, but as you saw each time I ran this gap is different.

**Comment by sj-aws** [comment]
Hi Daniel, thank you very much for sharing the results!

>  I let perf use the default event by not specifying -e and it shows similar mismatch problem with damo record

Ok, seems the bug is in `perf`, not `damo`.  I think we could ask help to `perf` community.

> And use sudo perf record -e damon:damon_aggregated -p $(pidof masim) to run again, but still cannot capture any result in perf.data.

I think that didn't work for two reasons.  First, you should manually set DAMON to monitor `$(pidof masim)`, and turn it on.  Second, the tracepoint event is created by not the monitoring target (`$(pidof masim)`), but DAMON worker thread called `kdamond.0`.  Hence, you should remove `$(pidof masim)` part.

Setting DAMON to monitor specific process and turning it on could be manually done using DAMON sysfs [interface](https://docs.kernel.org/admin-guide/mm/damon/usage.html#sysfs-interface).  Nevertheless, it would be not that convenient, so `damo` provides a command for that, namely `damo start`.  Using it, you could get the tracevents using perf like below:

```
$ sudo ./damo start "../masim/masim ../masim/configs/zigzag.cfg > /dev/null"
$ sudo perf record -e damon:damon_aggregated
^C[ perf record: Woken up 1 times to write data ]
[ perf record: Captured and wrote 0.323 MB perf.data (597 samples) ]

$ sudo perf script | head -n 1
       kdamond.0 27484 [008] 154828.982069: damon:damon_aggregated: target_id=0 nr_regions=13 94629863284736-94629864022016: 0 32
```

> The reason this mismatch is a problem to me is because

Thank you for the detailed explanation.  As mentioned above, I think we could ask further help to `perf` community.  Or, you could do the difference handling on your own.  `damo` provides relative time offset, so I think that shouldn't be too difficult.

I hope this answered all your question.  Is there anything you need more help from me with this ticket?

**Comment by sj-aws** [comment]
Thank you, please let me know if any further help is needed.  I think we can also make the time difference handling in `damo`.  E.g., compare the timestamps and update the perf-reported timestamp.  If you think it could be helpful, please feel free to let me know.  You may also open a new ticket for the feature request.
