### ISSUE TITLE
Does damo support multiple "damo record"?

### ISSUE THREAD

**Issue by honggyukim** [awslabs/damo#52]
Hi SeongJae,

I have tried to run `damo record` in two different terminals together while the other is running, but see that the second `damo record` gets the following failure.
```
$ sudo ./damo record -o damon.stairs3.data "./masim/masim ./masim/configs/stairs.cfg"
could not turn DAMON on (writing on to /sys/kernel/mm/damon/admin/kdamonds/0/state failed ([Errno 16] Device or resource busy))
```
As I understand, `/sys/kernel/mm/damon/admin/kdamonds/nr_kdamonds` can be larger than `1` and it can create multiple `kdamond`s, but I'm wondering why this failure is shown in `damo`.

I guess it might be a problem only in `damo`, but not from DAMON framework inside kernel.

Could you please confirm if my assumption is correct or not?

Thanks.

**Comment by honggyukim** [comment]
The same problem is shown with multiple `damo start`.

**Comment by sj-aws** [comment]
In short, your assumption is correct.  DAMON supports the use case, but `damo`'s current official interface doesn't support the use case.  We're aiming to support such use case with the next generation of the interface, though.  Please bear in mind with me until the next generation interface is ready.

Could you further clarify your use case in detail, though?  Maybe I could provide you some workaround, let you know some `damo` feature that not-yet-official but could be used for you, or adjust the next generation interface design to better fit your use case from the beginning of its official support.

**Comment by honggyukim** [comment]
> In short, your assumption is correct. DAMON supports the use case, but damo's current official interface doesn't support the use case.

Thanks for the confirmation. Then I think it’s fine now.

> Could you further clarify your use case in detail, though?

I can’t clearly state the concrete use case for now. I will think more and talk to other colleagues then get back to you.

Thanks for your help!

**Comment by sj-aws** [comment]
After 2024-09-05, we will[1] use damonitor repo[2] as the only main repo for GitHub.  To continue discussion of this issue on the repo, I just created a new issue[3] there.  Please use the new issue for followup discussions.

Closing this issue in favor of the new one on the damonitor repo. Please ask me to open this again if you cannot continue the discussion from the new issue.

[1] https://lore.kernel.org/20240813232158.83903-1-sj@kernel.org
[2] https://github.com/damonitor/damo
[3] https://github.com/damonitor/damo/issues/3
