### ISSUE TITLE
How to use filter in damo

### ISSUE THREAD

**Issue by hyeongtakji** [awslabs/damo#59]
Hello,

Is there anyway I can use [filters](https://docs.kernel.org/admin-guide/mm/damon/usage.html#schemes-n-filters) with damo? I could find some examples [here](https://github.com/awslabs/damo/blob/next/tests/schemes/prcl_no_cgroup_damos.json), but I'm not really used to using json with damo.

Or, can I use `-c` option along with normal usage like:
```
$ sudo damo schemes --damos_access_rate 0 0 --damos_sz_region 4K max \
                    --damos_age 60s max --damos_action pageout \
                    -c ./my_filter.json
                    <pid of your workload>
```
Also, any texts about the way to use json file will be useful to me.

Thanks!

**Comment by sj-aws** [comment]
Hello,


> Is there anyway I can use [filters](https://docs.kernel.org/admin-guide/mm/damon/usage.html#schemes-n-filters) with damo?  I could find some examples [here](https://github.com/awslabs/damo/blob/next/tests/schemes/prcl_no_cgroup_damos.json), but I'm not really used to using json with damo.

Currently, the json-based input is the only available one.  It is still not having good enough documentation, though.

> Or, can I use -c option along with normal usage like:

Unfortunately, no, at the moment.  We have a plan to provide that in future.

> Also, any texts about the way to use json file will be useful to me.

I agree, and that's also in the TODO list.  We are aiming to make at least the first draft of it before the version number exceeds 2.0.0.

**Comment by hyeongtakji** [comment]
Thank you for your quick answer.

> Currently, the json-based input is the only available one. 

Is there any plan to add filters options in damo?

> We are aiming to make at least the first draft of it before the version number exceeds 2.0.0.

Great to hear that! I will wait for it.

**Comment by sj-aws** [comment]
> Is there any plan to add filters options in damo?

Yes, we want to add it in a future, as a part of `--damos_*` options.  But, ETA is not clear at the moment.  We wish to make it before v2.0.0, though.

> Great to hear that! I will wait for it.

Thank you, please stay tuned!  Also, if this becomes urgent for you, please don't hesitate at asking escalation to me.

**Comment by sj-aws** [comment]
Commit bec360cce52c ("_damon_args: Support DAMOS filters via command line") implements the command line option for DAMOS filters.  Please read the commit message for more detailed usage.

Please note that the feature is not documented.  That means the feature is not stable yet, and the interface could be changed in a future.

**Comment by hyeongtakji** [comment]
Great! Glad that I can use filters with command line. I'll close this issue.
