### ISSUE TITLE
Print error when `--ops` is gonna be ignored

### ISSUE THREAD

**Issue by sj-aws** [awslabs/damo#60]
Following the discussion that made with https://github.com/awslabs/damo/issues/54, print error message whne `--ops` is gonna be ignored.  Specifically, when command or pid target argument is passed with `--ops` with `paddr`.

**Comment by sj-aws** [comment]
Fixed with above commit.  Now it shows warning of the overriding.  Please feel free to open this again if that doesn't fix your issue.

**Comment by honggyukim** [comment]
Thanks for fixing this problem!
