### ISSUE TITLE
Can I use multiple schemes with damo?

### ISSUE THREAD

**Issue by hyeongtakji** [awslabs/damo#61]
Hello,

I tried to apply two schemes with damo to find an error message like below.
```
$ sudo ./damo schemes --damos_access_rate 0 0 --damos_sz_region 4K max \
                    --damos_age 60s max --damos_action lru_deprio \
                    --ops paddr &
Press Ctrl+C to stop

$ sudo ./damo schemes --damos_access_rate 5 max --damos_sz_region 4K max \
                    --damos_age 0 1 --damos_action lru_prio \
                    --ops paddr &

could not turn DAMON on (writing on to /sys/kernel/mm/damon/admin/kdamonds/0/state failed ([Errno 16] Device or resource busy))
```

Is there any way I can apply multiple schemes (one kdamond, multiple schemes) with damo?

Thank you for your answer in advance.

**Comment by sj-aws** [comment]
Hi Hyeongtak,


> I tried to apply two schemes with damo to find an error message like below.

Only one instance of `damo` is allowed at the moment.  We don't have a plan to allow starting new `damo` instance while another one is running at the moment.  If this is important for your use case, please let me know your use case in more detail and why that's important, so that we could consider supporting the case.

> Is there any way I can apply multiple schemes (one kdamond, multiple schemes) with damo?

You could use `json` input for that.  It's not well documented at the moment, though, as I mentioned before.

**Comment by hyeongtakji** [comment]
In that case I believe I can refer to json files in `tests/schemes`. I think these will be enough for me.
Thank you!

**Comment by sj-aws** [comment]
Hi Hyeongtak, hope you're using the json file-based methods.  Though you mentioned you're ok with the json option, I felt this feature could be useful.  So I implemented it, as commit ed611e287048 ("_damon_args: Support multiple schemes").  If you still want it, please try it and feel free to report any bug that you find.

**Comment by honggyukim** [comment]
Hi SeongJae,

Although we can use json file, but command line support is still valuable because we had to keep showing the content of json file but we can now clearly show the exact usage with a single command line with this work.

Thanks very much for your support again.

**Comment by sj-aws** [comment]
Glad to hear that.  And thank you for enlightening me to know this kind of important and useful use case!

I'm basically very bad at UI design, but this kind of real use case feedback greatly helps me.
