### ISSUE TITLE
paddr is not supported

### ISSUE THREAD

**Issue by Yitrus** [awslabs/damo#86]
Hi,

I intend to sample each NUMA node individually, so I have chosen to sample using physical addresses. 

I am examining the address range of System RAM by using 'cat proc/iomem' and converting the hexadecimal values to decimal. My input is as follows:
`sudo damo record --numa_node 0 --ops paddr -r "4294967296-139586437119" --monitoring_nr_regions 10 100 -s 5000`

However, I have encountered errors for the addresses I have tried:
`could not turn DAMON on (cannot apply kdamonds from args (staging kdamond failed (paddr is not supported)))`

How can I make these addresses supported? Or, how can I determine which addresses are supported?

Thanks!

**Comment by Yitrus** [comment]
Hi SeongJae,

Thank you for your assistance! 

`
5.15.19
CONFIG_DAMON=y
CONFIG_DAMON_VADDR=Y
CONFIG_DAMON_DBGFS=y
`

I overlooked the fact that sampling the physical address space requires a higher kernel version. Thank you for pointing that out.

**Comment by sj-aws** [comment]
No problem, please feel free to let me know anything that I could help :)
